"""Render tests/detection_matrix.toml into the README and docs tables.

The TOML is the single source of truth for every detection claim: the test
suite executes it, this script renders it, and CI runs ``--check`` so the
documentation can never drift from what the tests actually verify.
"""

from __future__ import annotations

import sys
from pathlib import Path

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

ROOT = Path(__file__).parent.parent
MATRIX = ROOT / "tests" / "detection_matrix.toml"
README = ROOT / "README.md"
DOC = ROOT / "docs" / "detection-matrix.md"

START = "<!-- detection-matrix:start (generated by scripts/gen_detection_matrix_doc.py) -->"
END = "<!-- detection-matrix:end -->"

TIER_LABEL = {
    "detect": "**designed to detect**",
    "best-effort": "best-effort",
    "none": "not detected",
}


def render_table() -> str:
    cases = tomllib.loads(MATRIX.read_text(encoding="utf-8"))["case"]
    lines = [
        "| manipulation | example tested | status | test row |",
        "|---|---|---|---|",
    ]
    for c in cases:
        lines.append(
            f"| {c['family']} | {c['description']} | {TIER_LABEL[c['tier']]} | `{c['id']}` |"
        )
    return "\n".join(lines)


def render_block() -> str:
    test_link = (
        "[`tests/integration/test_detection_matrix.py`](tests/integration/test_detection_matrix.py)"
    )
    return (
        f"{START}\n{render_table()}\n\n"
        f"*Every row of this table is an executable test:* {test_link} "
        "*generates each manipulation with ffmpeg and asserts the stated status - "
        'rows marked "not detected" are asserted too, so the table can neither '
        "over-claim nor under-claim.*\n"
        f"{END}"
    )


def render_doc() -> str:
    return (
        "# Detection matrix\n\n"
        "> Generated from [`tests/detection_matrix.toml`](../tests/detection_matrix.toml) "
        "by `scripts/gen_detection_matrix_doc.py` - do not edit by hand.\n\n"
        "This is the complete, honest statement of what overlap detects. "
        "Detection tiers:\n\n"
        "- **designed to detect** - verified by a hard-failing test on generated fixtures\n"
        "- **best-effort** - sometimes caught; the test records but does not require it\n"
        "- **not detected** - beyond the current technique; asserted in tests so a "
        "capability improvement forces a documentation update\n\n"
        + render_table()
        + "\n\nSee [claim-hygiene.md](claim-hygiene.md) for the wording rules that keep "
        "every documented claim tied to a row of this matrix.\n"
    )


def splice_readme(readme_text: str, block: str) -> str:
    start_idx = readme_text.find(START)
    end_idx = readme_text.find(END)
    if start_idx == -1 or end_idx == -1:
        raise SystemExit("README.md is missing the detection-matrix markers")
    return readme_text[:start_idx] + block + readme_text[end_idx + len(END) :]


def main(check: bool) -> int:
    block = render_block()
    new_readme = splice_readme(README.read_text(encoding="utf-8"), block)
    new_doc = render_doc()
    if check:
        ok = (
            README.read_text(encoding="utf-8") == new_readme
            and DOC.exists()
            and DOC.read_text(encoding="utf-8") == new_doc
        )
        if not ok:
            print(
                "detection matrix docs are out of sync with tests/detection_matrix.toml;"
                " run: python scripts/gen_detection_matrix_doc.py",
                file=sys.stderr,
            )
            return 1
        print("detection matrix docs are in sync")
        return 0
    README.write_text(new_readme, encoding="utf-8", newline="\n")
    DOC.parent.mkdir(exist_ok=True)
    DOC.write_text(new_doc, encoding="utf-8", newline="\n")
    print(f"wrote {README} and {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(check="--check" in sys.argv))
